### ISSUE TITLE
Capture metadata that is still missing from wordpress to markdown export

### ISSUE THREAD

**Issue by PhilippeduPreez** [flowershow/wordpress-export-to-markdown-plus#12]
Capture all metadata with existing wordpress to markdown tool so we can use it as needed

## Acceptance
- [ ] Capture all important metadata

## Tasks
- [ ] Note which metadata is not currently being captured
- [ ] Capture this missing metadata
