### ISSUE TITLE
Incorporate outstanding pull requests from upstream

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/wordpress-export-to-markdown-plus#5]
Variety of useful outstanding pull requests against upstream that haven't been merged (and prob won't be) https://github.com/lonekorean/wordpress-export-to-markdown/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

## Tasks

- [ ] review outstanding pull requests
- [ ] for relevant ones invite submitter to submit here
- [ ] wait
- [ ] if no action could incorporate directly
